In [60]:
import numpy as np
import pandas as pd 

In [3]:
import numpy as np
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))
my_arr


array([     0,      1,      2, ..., 999997, 999998, 999999])

In [28]:
rng = np.random.default_rng()
arr2d=rng.integers(1,49,size=(3,6))
arr2d

array([[10, 17, 21, 37,  2,  3],
       [ 5,  7, 35, 24, 14, 42],
       [23, 47, 34,  9, 18,  8]])

In [29]:
# Get the first two rows
arr2d[:2, :]


array([[10, 17, 21, 37,  2,  3],
       [ 5,  7, 35, 24, 14, 42]])

In [30]:
# selects all elements in the third row of a two-dimensional array.
arr2d[2, :]

array([23, 47, 34,  9, 18,  8])

In [31]:

# Get all rows for the first two columns
arr2d[:, :2]


array([[10, 17],
       [ 5,  7],
       [23, 47]])

In [32]:
# Get all rows for the third column
arr2d[:, 2]


array([21, 35, 34])

In [33]:
# Access a specific element (row 1, column 2)
arr2d[1, 2]

35

In [34]:
arr2d[1][2] = 12

In [35]:
arr2d

array([[10, 17, 21, 37,  2,  3],
       [ 5,  7, 12, 24, 14, 42],
       [23, 47, 34,  9, 18,  8]])

In [42]:
arr1 = rng.integers(1,49,size=(3,6))
arr2 = rng.integers(1,49,size=(6,3))
arr1

array([[30,  3, 47,  6, 44, 46],
       [17,  2, 10,  5, 46,  8],
       [18, 45, 14, 42, 43, 28]])

In [43]:
arr2

array([[31, 19,  9],
       [25, 37, 34],
       [24, 18, 47],
       [31,  2, 29],
       [ 7, 12, 17],
       [40, 44, 24]])

In [44]:
# compute the union of arr1 and arr2
np.union1d(arr1, arr2)

array([ 2,  3,  5,  6,  7,  8,  9, 10, 12, 14, 17, 18, 19, 24, 25, 28, 29,
       30, 31, 34, 37, 40, 42, 43, 44, 45, 46, 47])

In [56]:
# compute the dot product of arr1 and arr2
np.dot(arr1, arr2)

# assign arr3 as the matrix multiplication of arr1 and arr2
arr3 = np.matmul(arr1, arr2)
arr3

array([[4467, 4091, 4607],
       [1614, 1491, 1810],
       [4742, 4091, 4971]])

In [57]:
# compute the inverse of arr2, conditioned on arr2 being a square matrix
np.linalg.inv(arr3)

array([[ 4.19173307e-05, -8.85265964e-03,  3.18451032e-03],
       [ 3.32809695e-03,  2.13458552e-03, -3.86162592e-03],
       [-2.77892106e-03,  6.68813572e-03,  3.41372696e-04]])

In [61]:
# create a new series with default index and the data [2.4, 4.0, 5.5, 6.75]
pd.Series([2.4, 4.0, 5.5, 6.75])

0    2.40
1    4.00
2    5.50
3    6.75
dtype: float64

In [63]:
# Create a sample DataFrame with mixed types
dft = pd.DataFrame({
    'A': np.random.randint(0, 100, 10),
    'B': np.random.rand(10),
    'C': np.random.randint(0, 100, 10).astype('uint'),
    'D': ['text'] * 10
})

In [64]:
# drop the columns 'two' and 'four' from the DataFrame dft
dft.drop(columns=['B', 'D'])

A   C
0  65  50
1  39   0
2  24  37
3  36  16
4  37  87
5  51   1
6  20  77
7  59   4
8  68  72
9  59  10

In [65]:
# or althernatively
dft.drop(['B', 'D'], axis=1)

A   C
0  65  50
1  39   0
2  24  37
3  36  16
4  37  87
5  51   1
6  20  77
7  59   4
8  68  72
9  59  10

In [ ]:
# rank dft over the columns
dft.rank(axis=0)


A     B     C    D
0   9.0   7.0   7.0  5.5
1   5.0   6.0   1.0  5.5
2   2.0   5.0   6.0  5.5
3   3.0   8.0   5.0  5.5
4   4.0   1.0  10.0  5.5
5   6.0   3.0   2.0  5.5
6   1.0   4.0   9.0  5.5
7   7.5   2.0   3.0  5.5
8  10.0  10.0   8.0  5.5
9   7.5   9.0   4.0  5.5

In [80]:
# alternatively
dft.rank()  # default axis is 0

A     B     C    D
0   9.0   7.0   7.0  5.5
1   5.0   6.0   1.0  5.5
2   2.0   5.0   6.0  5.5
3   3.0   8.0   5.0  5.5
4   4.0   1.0  10.0  5.5
5   6.0   3.0   2.0  5.5
6   1.0   4.0   9.0  5.5
7   7.5   2.0   3.0  5.5
8  10.0  10.0   8.0  5.5
9   7.5   9.0   4.0  5.5

In [84]:

dft.rank(axis=1)

/tmp/ipykernel_11351/2081008758.py:1: FutureWarning: Dropping of nuisance columns in DataFrame.rank is deprecated; in a future version this will raise TypeError. Select only valid columns before calling rank.
  dft.rank(axis=1)


A    B    C
0  3.0  1.0  2.0
1  3.0  2.0  1.0
2  2.0  1.0  3.0
3  3.0  1.0  2.0
4  2.0  1.0  3.0
5  3.0  1.0  2.0
6  2.0  1.0  3.0
7  3.0  1.0  2.0
8  2.0  1.0  3.0
9  3.0  1.0  2.0

In [88]:
# combine_first example, merging two DataFrames by filling in missing values from another DataFrame.
# if no missing values, the original DataFrame is returned unchanged.
from numpy import NaN


df1 = pd.DataFrame({
    'A': [1, 2, NaN],
    'B': [4, 5, 6]
})
df2 = pd.DataFrame({
    'A': [7, 8, 9],
    'B': [10, 11, 12]
})
df1.combine_first(df2)

A  B
0  1.0  4
1  2.0  5
2  9.0  6

In [75]:
# return unique values of index pd.Index(['a', 'b', 'c', 'a', 'b'])
pd.Index(['a', 'b', 'c', 'a', 'b']).unique()

Index(['a', 'b', 'c'], dtype='object')

In [77]:
# create a new column 'age' in a DataFrame df with a scalar value 25
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David']
})
df['age'] = 25
df

name  age
0    Alice   25
1      Bob   25
2  Charlie   25
3    David   25

In [78]:
# what is the purpose of the isna and notna methods in pandas?
# The isna() method in pandas is used to detect missing values (NaN) in a DataFrame or Series, returning a boolean mask indicating the presence of NaN values. 
# Conversely, the notna() method returns a boolean mask indicating the presence of non-missing values

# what is the purpose of the na_position parameter in the pandas sort_values method?
# The na_position parameter in the pandas sort_values method specifies the position of NaN values in
# the sorted result. It can take two values: 'first' (default) places NaNs at the beginning, 
# while 'last' places them at the end of the sorted data.
df = pd.DataFrame({
    'A': [3, 1, np.nan, 2],
    'B': [np.nan, 2, 3, 1]
})
df.sort_values(by='A', na_position='last')  # NaNs at the end




A    B
1  1.0  2.0
3  2.0  1.0
0  3.0  NaN
2  NaN  3.0

In [9]:
dft

A         B   C     D
0  50  0.670366  10  text
1   2  0.085878  87  text
2  97  0.604002  63  text
3  29  0.576267  48  text
4  39  0.809145  22  text
5  61  0.654717  28  text
6  66  0.862545  73  text
7  72  0.915061   3  text
8  36  0.617312  89  text
9  58  0.759686  89  text

In [7]:
# Select all numeric columns except float from the DataFrame dft
dft.select_dtypes(include=['int', 'uint'])

A   C
0  50  10
1   2  87
2  97  63
3  29  48
4  39  22
5  61  28
6  66  73
7  72   3
8  36  89
9  58  89

In [8]:
#return the last 3 rows of the DataFrame dft
dft.tail(3)

A         B   C     D
7  72  0.915061   3  text
8  36  0.617312  89  text
9  58  0.759686  89  text

In [ ]:
# what is the difference between loc and iloc in pandas?
# loc is label-based, allowing selection by row/column labels, 
# while iloc is integer-based, allowing selection by row/column positions.

In [85]:
frame=pd.DataFrame({
    'A': [10, 20, 30],
    'B': [15, 25, 35],
    'C': [20, 30, 40]
})
frame

A   B   C
0  10  15  20
1  20  25  30
2  30  35  40

In [86]:
frame.rank(axis='columns')

A    B    C
0  1.0  2.0  3.0
1  1.0  2.0  3.0
2  1.0  2.0  3.0

In [87]:
frame.rank(axis=1)

A    B    C
0  1.0  2.0  3.0
1  1.0  2.0  3.0
2  1.0  2.0  3.0

In [ ]:
frame.rank()